# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY api/ /app/api/
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Environment variables
ENV MODE=api
ENV LOG_LEVEL=INFO

# Expose the API port
EXPOSE 5001

# Command to run the API server
CMD ["python", "api/main.py"]
